# Black formatting
[tool.black]
line-length = 79
include = '\.pyi?$'
exclude = '''
/(
      \.eggs         # exclude a few common directories in the
    | \.git          # root of the project
    | \.hg
    | \.mypy_cache
    | \.tox
    | \.venv
    | _build
    | buck-out
    | build
    | dist
  )/
'''

# iSort
[tool.isort]
profile = "black"
line_length = 79
multi_line_output = 3
include_trailing_comma = true
skip_gitignore = true
virtual_env = "venv"

# Pytest
[tool.pytest.ini_options]
testpaths = [
    "tests",
]

# tagifai
[tool.setuptools]
name = "tagifai"
version = "0.1"
license = "MIT"
description = "Tag suggestions for projects on Made With ML."
author = "Goku Mohandas"
author_email = "hello@madewithml.com"
url = "https://madewithml.com/"
keywords = [
    "machine-learning",
    "artificial-intelligence",
    "madewithml",
]
classifiers = [
    "Development Status :: 3 - Alpha",
    "Intended Audience :: Developers",
    "Topic :: Software Development :: Build Tools",
    "License :: OSI Approved :: MIT License",
    "Programming Language :: Python :: 3",
]
python_requires = ">=3.6"
packages = ["tagifai"]
include_package_data = true
